#!/bin/sh

cd ${0%/*} || exit 1


rm -rf fluid/dynamicCode

rm -r fluid/0
rm -r fluid/postProcessing

foamListTimes -rm -case fluid


#------------------------------------------------------------------------------
