#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

export PYTHONPATH=${PWD}/../../structure/src/heatSolverFenicsX/src:$PYTHONPATH


cp -r fluid/0.orig fluid/0

blockMesh -case fluid

mpirun --np 1 buoyantPimpleFoam -case fluid -parallel -mpi-split-by-appnum : -np 1 python3 solid/solver.py 

postProcess -case fluid

#------------------------------------------------------------------------------``