#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

export PYTHONPATH=${PWD}/../structure/src/heatSolverPy/src:$PYTHONPATH
export PYTHONPATH=${PWD}/..coupling_lib/MUI/wrappers/Python:$PYTHONPATH


cp -r fluid/0.orig fluid/0

blockMesh -case fluid

mpirun --np 1 buoyantPimpleFoam -case fluid -parallel -mpi-split-by-appnum : -np 1 python3 solid/solver.py --length 0.20 --nodes 30 --alpha 4e-4 --kappa 1600

postProcess -case fluid

#------------------------------------------------------------------------------``